Repository SOL-Child/SOL-Family, pull requests merged in 2023-09, with the labels that each got.

#11 feat : #2 - 회원가입 및 휴대폰 인증 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/common/apis/authInstance.tsx
  frontend/src/common/apis/authInterceptors.tsx
  frontend/src/common/apis/instance.tsx
  frontend/src/common/interfaces/certifInfo.types.ts
  frontend/src/common/interfaces/loginUserInfo.types.ts
  frontend/src/common/interfaces/userInfo.types.ts
  frontend/src/features/Signup/apis/SignupAPI.tsx
  frontend/src/features/Signup/components/IntroPage/IntroPage.module.css
  frontend/src/features/Signup/components/IntroPage/IntroPage.tsx
  frontend/src/features/Signup/components/NamePage/NamePage.module.css
  frontend/src/features/Signup/components/NamePage/NamePage.tsx
  frontend/src/features/Signup/components/PasswordPage/PasswordPage.module.css
  frontend/src/features/Signup/components/PasswordPage/PasswordPage.tsx
  frontend/src/features/Signup/components/PhonePage/PhonePage.module.css
  frontend/src/features/Signup/components/PhonePage/PhonePage.tsx
  frontend/src/features/Signup/components/RolePage/RolePage.module.css
  frontend/src/features/Signup/components/RolePage/RolePage.tsx
  frontend/src/pages/SignupPage.module.css
  frontend/src/pages/SignupPage.tsx
  frontend/src/pages/SignupPage/SignupPage.module.css
  frontend/src/pages/SignupPage/SignupPage.tsx
Labels: ✨ 기능

#12 feat(LoginAPI.tsx) : #3 - 로그인 통신 구현
  frontend/src/features/Login/apis/LoginAPI.tsx
  frontend/src/features/Login/utils/LocalStorageUtil.tsx
  frontend/src/pages/LoginPage/LoginPage.module.css
  frontend/src/pages/LoginPage/LoginPage.tsx
Labels: ✨ 기능

#14 feat(Token) : #2 - jwt token 기능 구현
  backend/authentication-service/src/main/java/com/authenticationservice/AuthenticationServiceApplication.java
  backend/authentication-service/src/main/java/com/authenticationservice/global/dto/BaseResponseBody.java
  backend/authentication-service/src/main/java/com/authenticationservice/global/entity/Time.java
  backend/authentication-service/src/main/java/com/authenticationservice/global/util/SecurityUtil.java
  backend/authentication-service/src/main/java/com/authenticationservice/token/TokenController.java
  backend/authentication-service/src/main/java/com/authenticationservice/token/config/JwtProperties.java
  backend/authentication-service/src/main/java/com/authenticationservice/token/config/TokenAuthenticationFilter.java
  backend/authentication-service/src/main/java/com/authenticationservice/token/config/TokenProvider.java
  backend/authentication-service/src/main/java/com/authenticationservice/token/dto/request/CreateAccessTokenReqDto.java
  backend/authentication-service/src/main/java/com/authenticationservice/token/dto/response/CreateAccessTokenResDto.java
  backend/authentication-service/src/main/java/com/authenticationservice/token/dto/response/CreateTokenResDto.java
  backend/authentication-service/src/main/java/com/authenticationservice/token/entity/Token.java
  backend/authentication-service/src/main/java/com/authenticationservice/token/repository/JpaTokenRepository.java
  backend/authentication-service/src/main/java/com/authenticationservice/token/service/TokenService.java
  backend/authentication-service/src/main/java/com/authenticationservice/token/service/TokenServiceImpl.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/entity/Auth.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/entity/User.java
Labels: ✨ 기능

#16 feat(sms) : #15 - 전화번호 인증 기능 구현
  backend/authentication-service/build.gradle
  backend/authentication-service/src/main/java/com/authenticationservice/AuthenticationServiceApplication.java
  backend/authentication-service/src/main/java/com/authenticationservice/sms/SmsController.java
  backend/authentication-service/src/main/java/com/authenticationservice/sms/dao/SmsDao.java
  backend/authentication-service/src/main/java/com/authenticationservice/sms/dto/request/SmsReqDto.java
  backend/authentication-service/src/main/java/com/authenticationservice/sms/dto/request/SmsSendReqDto.java
  backend/authentication-service/src/main/java/com/authenticationservice/sms/properties/SmsProperties.java
  backend/authentication-service/src/main/java/com/authenticationservice/sms/service/SmsService.java
  backend/authentication-service/src/main/java/com/authenticationservice/sms/service/SmsServiceImpl.java
  backend/authentication-service/src/main/java/com/authenticationservice/sms/utill/MakeRandomNumber.java
  backend/authentication-service/src/main/java/com/authenticationservice/sms/utill/SmsMessageTemplate.java
Labels: ✨ 기능

#17 feat(signup) : #2 - 회원가입 기능 구현
  backend/authentication-service/src/main/java/com/authenticationservice/config/SecurityConfig.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/UserController.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/dto/request/UserReqDto.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/repository/JpaUserRepository.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/service/UserService.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/service/UserServiceImpl.java
Labels: ✨ 기능

#18 feat(SignIn) : #3 - 로그인 기능 구현
  backend/authentication-service/src/main/java/com/authenticationservice/config/SwaggerConfig.java
  backend/authentication-service/src/main/java/com/authenticationservice/token/config/TokenProvider.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/UserController.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/dto/request/LoginReqDto.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/dto/request/UserReqDto.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/dto/response/UserResDto.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/entity/User.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/entity/UserType.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/service/UserService.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/service/UserServiceImpl.java
  backend/authentication-service/src/main/resources/application.yml
Labels: ✨ 기능

#22 feat : #19 - 회원가입 통신 기능 구현
  frontend/src/common/apis/instance.tsx
  frontend/src/common/interfaces/certifInfo.types.ts
  frontend/src/common/interfaces/loginUserInfo.types.ts
  frontend/src/common/interfaces/userInfo.types.ts
  frontend/src/common/types/user.types.ts
  frontend/src/features/Signup/apis/SignupAPI.tsx
  frontend/src/features/Signup/components/PhonePage/PhonePage.tsx
  frontend/src/pages/SignupPage/SignupPage.tsx
Labels: ✨ 기능

#23 feat : #20 - 로그인 통신 기능 구현
  frontend/src/features/Login/apis/LoginAPI.tsx
  frontend/src/features/Login/utils/LocalStorageUtil.tsx
  frontend/src/pages/LoginPage/LoginPage.tsx
Labels: ✨ 기능

#29 feat(Exception) : #28 - 예외 처리 커스텀 구현
  backend/authentication-service/src/main/java/com/authenticationservice/global/error/ErrorCode.java
  backend/authentication-service/src/main/java/com/authenticationservice/global/error/ExceptionHandler.java
  backend/authentication-service/src/main/java/com/authenticationservice/global/error/exception/AuthenticationException.java
  backend/authentication-service/src/main/java/com/authenticationservice/global/error/exception/BusinessException.java
  backend/authentication-service/src/main/java/com/authenticationservice/token/service/TokenServiceImpl.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/service/UserServiceImpl.java
Labels: ✨ 기능

#30 feat : #13 - 메인페이지 공통 컴포넌트 구현
  frontend/public/manifest.json
  frontend/src/App.tsx
  frontend/src/common/components/BottomBar/BottomBar.module.css
  frontend/src/common/components/BottomBar/BottomBar.tsx
  frontend/src/common/components/ContentsFrame/ContentsFrame.module.css
  frontend/src/common/components/ContentsFrame/ContentsFrame.tsx
  frontend/src/common/components/Header/Header.module.css
  frontend/src/common/components/Header/Header.tsx
  frontend/src/common/constants/Pages.ts
  frontend/src/common/constants/User.ts
  frontend/src/common/hooks/useFetch.tsx
  frontend/src/common/images/SF_full_logo.png
  frontend/src/common/images/SF_home_icon.png
  frontend/src/common/images/SF_link_icon.png
  frontend/src/common/images/SF_loan_icon.png
  frontend/src/common/images/SF_mission_icon.png
  frontend/src/common/images/SF_notice_selected_icon.png
  frontend/src/common/images/SF_notice_unselected_icon.png
  frontend/src/common/images/SF_person_selected_icon.png
  frontend/src/common/images/SF_person_unselected_icon.png
  frontend/src/common/images/SF_pinmoney_icon.png
  frontend/src/common/images/SF_shinhan_icon.png
  frontend/src/common/types/user.types.ts
  frontend/src/features/Main/components/AccountBox/AccountBox.module.css
  frontend/src/features/Main/components/AccountBox/AccountBox.tsx
  frontend/src/features/Main/components/FamilyBox/FamilyBox.module.css
  frontend/src/features/Main/components/FamilyBox/FamilyBox.tsx
  frontend/src/features/Main/components/MainContents/MainContents.module.css
  frontend/src/features/Main/components/MainContents/MainContents.tsx
  frontend/src/features/Main/components/MainMenuBox/MainMenuBox.module.css
  frontend/src/features/Main/components/MainMenuBox/MainMenuBox.tsx
  frontend/src/features/Main/utils/MainUtil.ts
  frontend/src/pages/LoginPage/LoginPage.module.css
  frontend/src/pages/LoginPage/LoginPage.tsx
  frontend/src/pages/MainPage/MainPage.module.css
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/SignupPage/SignupPage.module.css
Labels: ✨ 기능

#36 feat(Fund) : #35 - 펀드 상품
  backend/account-service/build.gradle
  backend/account-service/src/main/java/com/accountservice/AccountServiceApplication.java
  backend/account-service/src/main/java/com/accountservice/fund/FundController.java
  backend/account-service/src/main/java/com/accountservice/fund/entity/Fund.java
  backend/account-service/src/main/java/com/accountservice/fund/repository/JpaFundRepository.java
  backend/account-service/src/main/java/com/accountservice/fund/service/FundService.java
  backend/account-service/src/main/java/com/accountservice/fund/service/FundServiceImpl.java
  backend/account-service/src/main/java/com/accountservice/global/dto/BaseResponseBody.java
Labels: ✨ 기능

#31 feat(Modal) : #27 - 공통 모달 컴포넌트 구현
  frontend/src/common/components/Modal/Modal.module.css
  frontend/src/common/components/Modal/Modal.tsx
  frontend/src/features/Main/components/MainMenuBox/MainMenuBox.tsx
Labels: ✨ 기능

#40 feat(InstallmentSavings) : #37 - 적금 상품
  backend/account-service/src/main/java/com/accountservice/installmentSavings/InstallmentSavingsController.java
  backend/account-service/src/main/java/com/accountservice/installmentSavings/entity/InstallmentSavings.java
  backend/account-service/src/main/java/com/accountservice/installmentSavings/repository/JpaInstallmentSavingsRepository.java
  backend/account-service/src/main/java/com/accountservice/installmentSavings/service/InstallmentSavingsService.java
  backend/account-service/src/main/java/com/accountservice/installmentSavings/service/InstallmentSavingsServiceImpl.java
Labels: ✨ 기능

#43 feat(Transfer) : #42 - 계좌 이체 페이지 및 모달 구현
  frontend/public/SF_small_logo.ico
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/common/components/ContentsFrame/ContentsFrame.module.css
  frontend/src/common/components/ContentsFrame/ContentsFrame.tsx
  frontend/src/common/components/PageFrame/PageFrame.module.css
  frontend/src/common/components/PageFrame/PageFrame.tsx
  frontend/src/common/components/PageHeader/PageHeader.module.css
  frontend/src/common/components/PageHeader/PageHeader.tsx
  frontend/src/common/constants/Pages.ts
  frontend/src/common/hooks/useInput.tsx
  frontend/src/common/images/SF_back_icon_blue.png
  frontend/src/common/images/SF_delete_button.png
  frontend/src/common/types/account.types.ts
  frontend/src/features/Account/apis/AccountAPI.ts
  frontend/src/features/Account/components/TransferCheckModal/TransferCheckModal.module.css
  frontend/src/features/Account/components/TransferCheckModal/TransferCheckModal.tsx
  frontend/src/features/Main/components/AccountBox/AccountBox.tsx
  frontend/src/pages/LoginPage/LoginPage.tsx
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/SignupPage/SignupPage.tsx
  frontend/src/pages/TransferPage/TransferPage.module.css
  frontend/src/pages/TransferPage/TransferPage.tsx
Labels: ✨ 기능

#44 feat(SignupAPI) : #19 - 회원가입 통신
  frontend/src/common/apis/authInstance.tsx
  frontend/src/common/apis/instance.tsx
  frontend/src/features/Main/components/MainMenuBox/MainMenuBox.tsx
  frontend/src/features/Signup/apis/SignupAPI.tsx
  frontend/src/features/Signup/components/PhonePage/PhonePage.tsx
  frontend/src/pages/SignupPage/SignupPage.module.css
Labels: ✨ 기능

#53 feat(LoanRequest) : #51 - 대출 신청 페이지 및 바텀시트 구현
  frontend/src/App.tsx
  frontend/src/common/components/BottomSheet/BottomSheet.module.css
  frontend/src/common/components/BottomSheet/BottomSheet.tsx
  frontend/src/common/components/ContentsFrame/ContentsFrame.tsx
  frontend/src/common/constants/Pages.ts
  frontend/src/features/Loan/components/LoanUsageBottomSheet/LoanUsageBottomSheet.module.css
  frontend/src/features/Loan/components/LoanUsageBottomSheet/LoanUsageBottomSheet.tsx
  frontend/src/features/Main/components/MainMenuBox/MainMenuBox.tsx
  frontend/src/index.css
  frontend/src/pages/LoanRequestPage/LoanRequestPage.module.css
  frontend/src/pages/LoanRequestPage/LoanRequestPage.tsx
Labels: ✨ 기능

#38 feat(deploy) : jenkinsfile, docker-compose, dockerfile 추가
  backend/authentication-service/Dockerfile
  backend/authentication-service/build.gradle
  backend/authentication-service/src/main/java/com/authenticationservice/config/DataSourceConfig.java
  backend/authentication-service/src/main/java/com/authenticationservice/config/SecurityConfig.java
  backend/authentication-service/src/main/java/com/authenticationservice/config/Webconfig.java
  backend/authentication-service/src/main/java/com/authenticationservice/kms/KmsConfig.java
  backend/authentication-service/src/main/java/com/authenticationservice/kms/KmsService.java
  backend/authentication-service/src/main/java/com/authenticationservice/token/config/TokenProvider.java
  backend/authentication-service/src/main/resources/application.yml
  docker-compose.yml
  jenkinsfile
Labels: ✨ 기능, 🚀 배포

#64 feat(Family) : #58 - 가족 연결 기능 구현
  backend/authentication-service/build.gradle
  backend/authentication-service/src/main/java/com/authenticationservice/config/SecurityConfig.java
  backend/authentication-service/src/main/java/com/authenticationservice/family/FamilyController.java
  backend/authentication-service/src/main/java/com/authenticationservice/family/dto/request/FamilyReqDto.java
  backend/authentication-service/src/main/java/com/authenticationservice/family/entity/Family.java
  backend/authentication-service/src/main/java/com/authenticationservice/family/exception/InvalidFamilyCodeException.java
  backend/authentication-service/src/main/java/com/authenticationservice/family/repository/JpaFamilyRepository.java
  backend/authentication-service/src/main/java/com/authenticationservice/family/service/FamilyService.java
  backend/authentication-service/src/main/java/com/authenticationservice/family/service/FamilyServiceImpl.java
  backend/authentication-service/src/main/java/com/authenticationservice/global/error/ErrorCode.java
  backend/authentication-service/src/main/java/com/authenticationservice/global/error/exception/ValidationException.java
  backend/authentication-service/src/main/java/com/authenticationservice/sms/SmsController.java
  backend/authentication-service/src/main/java/com/authenticationservice/token/config/TokenProvider.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/UserController.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/entity/User.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/exception/DuplicatePhoneException.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/service/UserService.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/service/UserServiceImpl.java
Labels: ✨ 기능

#65 fix(Family) : #58 - 가족 연결 버그 수정
  backend/authentication-service/src/main/java/com/authenticationservice/family/entity/Family.java
  backend/authentication-service/src/main/java/com/authenticationservice/family/service/FamilyServiceImpl.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/UserController.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/dto/response/UserResDto.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/entity/User.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/repository/JpaUserRepository.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/service/UserService.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/service/UserServiceImpl.java
Labels: 🐛 버그, ✨ 기능, ⚡️ 개선

#66 fix(Loan) : #59, #60 - 대출 기능 구현
  backend/account-service/src/main/java/com/accountservice/global/utill/Time.java
  backend/account-service/src/main/java/com/accountservice/loan/LoanController.java
  backend/account-service/src/main/java/com/accountservice/loan/dto/request/LoanReqDto.java
  backend/account-service/src/main/java/com/accountservice/loan/dto/response/LoanResDto.java
  backend/account-service/src/main/java/com/accountservice/loan/entity/Loan.java
  backend/account-service/src/main/java/com/accountservice/loan/repository/JpaLoanRepository.java
  backend/account-service/src/main/java/com/accountservice/loan/service/LoanService.java
  backend/account-service/src/main/java/com/accountservice/loan/service/LoanServiceImpl.java
Labels: ✨ 기능

#68 fix(Autentication-service) : #67 - 문서화, 버그 수정, 기능 개선
  backend/authentication-service/build.gradle
  backend/authentication-service/src/main/java/com/authenticationservice/family/FamilyController.java
  backend/authentication-service/src/main/java/com/authenticationservice/family/exception/DuplicateFamilyCodeException.java
  backend/authentication-service/src/main/java/com/authenticationservice/family/service/FamilyServiceImpl.java
  backend/authentication-service/src/main/java/com/authenticationservice/global/error/ErrorCode.java
  backend/authentication-service/src/main/java/com/authenticationservice/sms/SmsController.java
  backend/authentication-service/src/main/java/com/authenticationservice/token/TokenController.java
  backend/authentication-service/src/main/java/com/authenticationservice/token/entity/Token.java
  backend/authentication-service/src/main/java/com/authenticationservice/token/service/TokenService.java
  backend/authentication-service/src/main/java/com/authenticationservice/token/service/TokenServiceImpl.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/UserController.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/service/UserService.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/service/UserServiceImpl.java
Labels: 🐛 버그, 📝 문서, ✨ 기능, ⚡️ 개선

#71 feat(Alarm) : #69, #70 - 알람 페이지 및 상세 정보 모달 구현
  frontend/src/App.tsx
  frontend/src/common/components/BottomBar/BottomBar.tsx
  frontend/src/common/components/ContentsFrame/ContentsFrame.tsx
  frontend/src/common/constants/Pages.ts
  frontend/src/common/images/SF_alarm_icon.png
  frontend/src/common/images/SF_alarm_selected_icon.png
  frontend/src/common/images/SF_alarm_unselected_icon.png
  frontend/src/common/images/SF_money_icon.png
  frontend/src/common/types/alarm.types.ts
  frontend/src/features/Alarm/components/AlarmModal/AlarmModal.module.css
  frontend/src/features/Alarm/components/AlarmModal/AlarmModal.tsx
  frontend/src/pages/AlarmPage/AlarmPage.module.css
  frontend/src/pages/AlarmPage/AlarmPage.tsx
Labels: ✨ 기능

#73 fix(FamilyController) : #58 - QR 바이트에서 이미지로 변환
  backend/authentication-service/src/main/java/com/authenticationservice/family/FamilyController.java
Labels: ✨ 기능, ⚡️ 개선

#81 feat(create-account) : #75 -계좌 생성
  backend/blockchain-service/.gitignore
  backend/blockchain-service/build.gradle
  backend/blockchain-service/gradle/wrapper/gradle-wrapper.jar
  backend/blockchain-service/gradle/wrapper/gradle-wrapper.properties
  backend/blockchain-service/gradlew
  backend/blockchain-service/gradlew.bat
  backend/blockchain-service/settings.gradle
  backend/blockchain-service/src/main/java/com/blockchainservice/BlockchainServiceApplication.java
  backend/blockchain-service/src/main/java/com/blockchainservice/ethereum/EthereumController.java
  backend/blockchain-service/src/main/java/com/blockchainservice/ethereum/entity/Ethereum.java
  backend/blockchain-service/src/main/java/com/blockchainservice/ethereum/repository/JpaEthereumRepository.java
  backend/blockchain-service/src/main/java/com/blockchainservice/ethereum/service/Encrypt.java
  backend/blockchain-service/src/main/java/com/blockchainservice/ethereum/service/EthereumService.java
  backend/blockchain-service/src/main/java/com/blockchainservice/ethereum/service/EthereumServiceImpl.java
  backend/blockchain-service/src/main/java/com/blockchainservice/global/dto/BaseResponseBody.java
  backend/blockchain-service/src/main/java/com/blockchainservice/global/entity/Time.java
  backend/blockchain-service/src/main/java/com/blockchainservice/global/error/ErrorCode.java
  backend/blockchain-service/src/main/java/com/blockchainservice/global/error/ExceptionHandler.java
  backend/blockchain-service/src/main/java/com/blockchainservice/global/error/exception/BusinessException.java
  backend/blockchain-service/src/main/java/com/blockchainservice/global/error/exception/ValidationException.java
  backend/blockchain-service/src/main/resources/application.yml
  backend/blockchain-service/src/test/java/com/blockchainservice/BlockchainServiceApplicationTests.java
Labels: ✨ 기능

#82 feat(API) : #19, #20 - 로그인, 회원가입 통신
  frontend/package-lock.json
  frontend/package.json
  frontend/src/common/apis/authInstance.tsx
  frontend/src/common/apis/instance.tsx
  frontend/src/common/constants/User.ts
  frontend/src/common/types/user.types.ts
  frontend/src/features/Login/apis/LoginAPI.tsx
  frontend/src/features/Login/utils/LocalStorageUtil.tsx
  frontend/src/features/Main/apis/QrcodeAPI.ts
  frontend/src/features/Main/components/FamilyBox/FamilyBox.tsx
  frontend/src/features/Main/components/QRModal/QRModal.module.css
  frontend/src/features/Main/components/QRModal/QRModal.tsx
  frontend/src/features/Main/components/QRScanner/QRScanner.module.css
  frontend/src/features/Main/components/QRScanner/QRScanner.tsx
  frontend/src/features/Signup/apis/SignupAPI.tsx
  frontend/src/features/Signup/components/PhonePage/PhonePage.tsx
  frontend/src/features/Signup/components/RolePage/RolePage.tsx
  frontend/src/pages/LoginPage/LoginPage.tsx
  frontend/src/pages/SignupPage/SignupPage.tsx
Labels: ✨ 기능

#83 feat(API) : #74 - API 규칙에 맞게 수정
  frontend/src/common/constants/url.ts
  frontend/src/common/hooks/useFetch.tsx
  frontend/src/common/types/user.types.ts
  frontend/src/features/Main/components/AccountBox/AccountBox.tsx
  frontend/src/features/Main/components/FamilyBox/FamilyBox.tsx
  frontend/src/features/Main/components/MainContents/MainContents.tsx
  frontend/src/features/Main/components/MainMenuBox/MainMenuBox.tsx
  frontend/src/features/Main/utils/MainUtil.ts
  frontend/src/pages/MainPage/MainPage.tsx
Labels: ✨ 기능

#84 feat(Ethereum) : #77 - 계좌 간 이체 구현
  backend/blockchain-service/src/main/java/com/blockchainservice/ethereum/EthereumController.java
  backend/blockchain-service/src/main/java/com/blockchainservice/ethereum/entity/BookType.java
  backend/blockchain-service/src/main/java/com/blockchainservice/ethereum/entity/Ethereum.java
  backend/blockchain-service/src/main/java/com/blockchainservice/ethereum/exception/AESException.java
  backend/blockchain-service/src/main/java/com/blockchainservice/ethereum/exception/InvalidEthereumException.java
  backend/blockchain-service/src/main/java/com/blockchainservice/ethereum/repository/JpaEthereumRepository.java
  backend/blockchain-service/src/main/java/com/blockchainservice/ethereum/service/AESEncryption.java
  backend/blockchain-service/src/main/java/com/blockchainservice/ethereum/service/Encrypt.java
  backend/blockchain-service/src/main/java/com/blockchainservice/ethereum/service/EthereumService.java
  backend/blockchain-service/src/main/java/com/blockchainservice/ethereum/service/EthereumServiceImpl.java
  backend/blockchain-service/src/main/java/com/blockchainservice/global/error/ErrorCode.java
  backend/blockchain-service/src/test/java/com/blockchainservice/AESKeyGenerator.java
Labels: ✨ 기능

#85 feat(EthereumService) : #78 - 거래내역 조회
  backend/blockchain-service/src/main/java/com/blockchainservice/ethereum/EthereumController.java
  backend/blockchain-service/src/main/java/com/blockchainservice/ethereum/service/EthereumService.java
  backend/blockchain-service/src/main/java/com/blockchainservice/ethereum/service/EthereumServiceImpl.java
  backend/blockchain-service/src/main/java/com/blockchainservice/global/config/WebConfig.java
Labels: ✨ 기능

#87 feat(Docker) : #86 - blockchain service 배포
  backend/blockchain-service/src/main/java/com/blockchainservice/Dockerfile
  backend/blockchain-service/src/main/resources/application.yml
  docker-compose.yml
  jenkinsfile
Labels: ✨ 기능, 🚀 배포

#88 fix(Dockerfile) : #86 - Dockerfile 위치 변경
  backend/blockchain-service/Dockerfile
Labels: 🐛 버그

#89 fix(EthereumController) : #86 - RequestHeader -> RequestParam
  backend/blockchain-service/src/main/java/com/blockchainservice/ethereum/EthereumController.java
Labels: 🚀 배포

#97 feat(TransactionPage) : #57 - 거래 내역 확인 페이지
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/common/components/ContentsFrame/ContentsFrame.module.css
  frontend/src/common/components/ContentsFrame/ContentsFrame.tsx
  frontend/src/common/components/ToggleBox/ToggleBox.module.css
  frontend/src/common/constants/Pages.ts
  frontend/src/common/images/SF_back_icon_white.png
  frontend/src/common/types/transaction.types.ts
  frontend/src/features/Account/components/Chart/Chart.tsx
  frontend/src/pages/FundPage/FundPage.module.css
  frontend/src/pages/FundPage/FundPage.tsx
  frontend/src/pages/TransactionPage/TransactionPage.module.css
  frontend/src/pages/TransactionPage/TransactionPage.tsx
Labels: ✨ 기능

#98 feat(fcm) : #76 - Firebase fcm 기능 구현
  backend/authentication-service/.gitignore
  backend/authentication-service/build.gradle
  backend/authentication-service/src/main/java/com/authenticationservice/fcm/FcmNotificationApiController.java
  backend/authentication-service/src/main/java/com/authenticationservice/fcm/config/FcmConfig.java
  backend/authentication-service/src/main/java/com/authenticationservice/fcm/dto/FcmNotificationRequestDto.java
  backend/authentication-service/src/main/java/com/authenticationservice/fcm/service/FcmNotificationService.java
  backend/authentication-service/src/main/java/com/authenticationservice/fcm/service/FcmNotificationServiceImpl.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/dto/request/UserReqDto.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/entity/User.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/service/UserServiceImpl.java
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/public/firebase-messaging-sw.js
  frontend/src/App.tsx
  frontend/src/common/types/user.types.ts
  frontend/src/firebase-messaging-sw.js
  frontend/src/pages/SignupPage/SignupPage.tsx
Labels: ✨ 기능

#99 feat(FcmNotificationServiceImpl) : #76 - 알림 보내기 로직 변경
  backend/authentication-service/src/main/java/com/authenticationservice/fcm/service/FcmNotificationServiceImpl.java
Labels: ✨ 기능

#100 feat(Account) : #95 - 계좌 이체 , 내역 조회
  backend/account-service/src/main/java/com/accountservice/account/AccountController.java
  backend/account-service/src/main/java/com/accountservice/account/config/RandomWordCombiner.java
  backend/account-service/src/main/java/com/accountservice/account/dto/request/ConnectReqDto.java
  backend/account-service/src/main/java/com/accountservice/account/dto/request/TransactionReqDto.java
  backend/account-service/src/main/java/com/accountservice/account/dto/request/TransferReqDto.java
  backend/account-service/src/main/java/com/accountservice/account/dto/response/MainResDto.java
  backend/account-service/src/main/java/com/accountservice/account/dto/response/TransactionDetailDto.java
  backend/account-service/src/main/java/com/accountservice/account/dto/response/TransactionResDto.java
  backend/account-service/src/main/java/com/accountservice/account/dto/response/TransferResDto.java
  backend/account-service/src/main/java/com/accountservice/account/entity/Account.java
  backend/account-service/src/main/java/com/accountservice/account/entity/BookType.java
  backend/account-service/src/main/java/com/accountservice/account/entity/OneTransfer.java
  backend/account-service/src/main/java/com/accountservice/account/entity/Transaction.java
  backend/account-service/src/main/java/com/accountservice/account/entity/Transfer.java
  backend/account-service/src/main/java/com/accountservice/account/exception/TransferCodeException.java
  backend/account-service/src/main/java/com/accountservice/account/repository/JpaAccountRepository.java
  backend/account-service/src/main/java/com/accountservice/account/repository/JpaOneTransferRepository.java
  backend/account-service/src/main/java/com/accountservice/account/repository/JpaTransactionRepository.java
  backend/account-service/src/main/java/com/accountservice/account/repository/JpaTransferRepository.java
  backend/account-service/src/main/java/com/accountservice/account/service/AccountService.java
  backend/account-service/src/main/java/com/accountservice/account/service/AccountServiceImpl.java
  backend/account-service/src/main/java/com/accountservice/config/DataSourceConfig.java
  backend/account-service/src/main/java/com/accountservice/global/entity/Time.java
  backend/account-service/src/main/java/com/accountservice/global/error/ErrorCode.java
  backend/account-service/src/main/java/com/accountservice/global/error/ExceptionHandler.java
  backend/account-service/src/main/java/com/accountservice/global/error/exception/BusinessException.java
  backend/account-service/src/main/java/com/accountservice/kms/KmsConfig.java
  backend/account-service/src/main/java/com/accountservice/kms/KmsService.java
  backend/account-service/src/main/java/com/accountservice/loan/entity/Loan.java
  backend/account-service/src/main/resources/words.txt
  backend/authentication-service/src/main/java/com/authenticationservice/family/FamilyController.java
  backend/authentication-service/src/main/java/com/authenticationservice/user/repository/JpaUserRepository.java
Labels: ✨ 기능
